# Generated by Django 5.1 on 2024-08-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0002_airport_alter_flight_destination_alter_flight_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aexirrivals",
                to="flights.airport",
            ),
        ),
    ]
