# Generated by Django 5.1 on 2024-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0004_alter_flight_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=64)),
                ("age", models.IntegerField()),
                (
                    "flights",
                    models.ManyToManyField(
                        blank=True, related_name="passengers", to="flights.flight"
                    ),
                ),
            ],
        ),
    ]
